	#ZSH Settings
DEFAULT_USER=$USER
ZSH_THEME="agnoster"
DISABLE_AUTO_UPDATE="true"
HIST_STAMPS="%Y-%m-%d %H:%M:%S %Z"

export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh
export HOMEBREW_NO_AUTO_UPDATE=1

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

## file types
alias -s c=vi
alias -s js=st
alias -s py=python

##Proxy
# Surge Proxy
export https_proxy=http://127.0.0.1:1225
export http_proxy=http://127.0.0.1:1225
export all_proxy=socks5://127.0.0.1:1226

noproxy (){
	unset https_proxy
	unset http_proxy
	unset all_proxy
	echo "Http Proxy off"
}

## command
alias cat='ccat'
alias tree='tree -N'
alias rm='rmtrash'
alias ggc='open -a "Google Chrome"'
alias go='git open'
alias gshred='gshred -f -n 25 -u -z -v'
alias ida='/Applications/idaq.app/Contents/MacOS/idaq64 &'
alias ok='curl https://api.day.app/mAqJ9ZxqtzZ65Cpz6KxVkL/Done'
alias airports='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport'

## fzf
alias vzf='vim "$(fzf)"'
alias czf='cd "$(find * -type d | fzf)"'

## nasm
alias comp='nasm -f macho'
alias link='ld -macosx_version_min 10.7.0 -o'

## tmux
alias tls='tmux ls'
alias tnew='tmux new -s'
alias tat='tmux at -t'
alias tkill='tmux kill-session -t'

## brew
alias bi='brew install'
alias bci='brew cask install'
alias br='brew remove'
alias bcr='brew cask remove'
alias bs='brew search'
alias be='brew edit'
alias bld='brew deps --tree --installed'
alias sha256="openssl dgst -sha256"
alias update="brew update && brew cask upgrade && brew cu -a -y && mas upgrade"

# Bin Path
export PATH=$HOME/.pyenv:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/opt/local/bin:$PATH
export PATH=/Library/TeX/texbin:$PATH         #pdflatex
export PATH=$HOME/bin:/usr/local/bin:$PATH    #系统命令
export PATH=/usr/local/anaconda3/bin:$PATH    #anaconda
export PATH=/usr/local/Cellar/nmap/7.70/bin:$PATH

# Custom Path
export THEOS=/opt/theos
export PATH=/opt/theos/bin/:$PATH
export PATH=$HOME/Dropbox/bin:$PATH
export PATH=/opt/MonkeyDev/bin:$PATH
export PATH=$HOME/Dropbox/.bin:$PATH          #工作环境
export MonkeyDevPath=/opt/MonkeyDev
export MonkeyDevDeviceIP=192.168.123.6


# Plugins
plugins=(
   autojump zsh-syntax-highlighting zsh-autosuggestions sublime sudo osx git extract
)

fag(){
j  line=`ag --nocolor '$1' | fzf` \
    && vim $(cut -d':' -f1 <<< '$line') +$(cut -d':' -f2 <<< '$line')
}

ckdir(){
  mkdir -p $1
  cd $1
}

bark(){
	echo $1|base64
	curl "https://api.day.app/设备标识符/"+$1
}